modLoader = "javafml"
loaderVersion = "[49,)"
issueTrackerURL = "https://github.com/luxmiyu/adm2/issues"
license = "MIT"

[[mods]]
modId = "adm2"
version = "${version}"
displayName = "Any Dimension Mod 2"
authors = "luxmiyu"
description = '''
Create dimensions out of any block! This mod adds 400+ dimensions to the game, one for each of the possible blocks.
'''
logoFile = "icon.png"

[[dependencies.adm2]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.adm2]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"
